import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Cronos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  notifications: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#E1EBF4]`}>

        <div className="absolute top-0 left-0 z-20">{children}</div>
      </body>
    </html>
  );
}
