import type { Metadata } from "next";
import HomePageLayout from "@/components/home-page-layout-navbar";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";


export const metadata: Metadata = {
  title: "Cronos",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
  notifications: React.ReactNode;
}) {



  return (
    <html lang="en">
      <body
        className={`antialiased bg-[E1EBF4]`}
      ><div className="fixed top-0 left-0 opacity-75 h-screen overflow-x-hidden">
          <BackgroundGradientAnimation />
        </div>
        <div className="absolute top-0 left-0">
          <HomePageLayout />
          {children}
        </div>
      </body>
    </html>
  );
}
